---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-storage-pv
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  storageClassName: standard
  local:
    path: /mnt/nginx-storage
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: Exists
              
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-storage
  namespace: nginx-namespace
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 8Gi
  storageClassName: standard

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-statefulset
  namespace: nginx-namespace
spec:
  serviceName: headless-svc
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: ghcr.io/mohtashims/secure-nginx:1.19-alpinebfd9045ea79a0cdc496733a599e5c8092d394dd9
          #imagePullPolicy: Never
          ports:
            - containerPort: 80
          securityContext:
            runAsUser: 1003
            runAsGroup: 1003
            capabilities:
              add: ["NET_BIND_SERVICE"]
              drop: ["ALL"]
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /
              port: 80
              #scheme: HTTP
            timeoutSeconds: 2
            initialDelaySeconds: 20
            periodSeconds: 5
            failureThreshold: 3
 
          readinessProbe:
            httpGet:
              path: /
              port: 80
              #scheme: HTTP
            timeoutSeconds: 2  
            initialDelaySeconds: 10
            periodSeconds: 3
            failureThreshold: 3
          volumeMounts:
            - name: nginx-html
              mountPath: /usr/share/nginx/html
      volumes:
        - name: nginx-html
          persistentVolumeClaim:
            claimName: nginx-storage
            
      imagePullSecrets:
        - name: github-container-registry        
---
apiVersion: v1
kind: Service
metadata:
  name: headless-svc
  namespace: nginx-namespace
spec:
  clusterIP: None
  selector:
    app: nginx
  ports:
    - name: https
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-loadbalancer
  namespace: nginx-namespace
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
